application: copper-mender-90613
version: 1
runtime: python27
api_version: 1
threadsafe: yes

# [START handlers]
handlers:
- url: /css
  static_dir: css

- url: /.*
  script: Stage 4 - Project.app
# [END handlers]

# [START libraries]
libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: latest
# [END libraries]

